### ISSUE TITLE
parseType does not handle type literals

### ISSUE THREAD

**Issue by thautwarm** [bmillwood/haskell-src-meta#87]
`parseType "1"` failed:

```
src\xxx.hs:41:6: error:
    • Exception when trying to run compile-time code:
        0
SrcLoc "" 1 2
DataKinds language extension is not enabled. Please add {-# LANGUAGE DataKinds #-} pragma at the top of your module.
```

However so far it is impossible to specify it because the parse mode for `parseType` is hardcoded.

**Comment by thautwarm** [comment]
something like [this](https://github.com/thautwarm/Metagen/blob/239e1e7503f70bd8a2ad8730a738e036a89876b5/src/Metagen/MetaParsePatch.hs#L28) may be nice to have.

**Comment by mainland** [comment]
Dan Burton took over the library a few years ago: https://github.com/danburton/haskell-src-meta

**Comment by thautwarm** [comment]
@mainland Thanks.

**Comment by thautwarm** [comment]
Well, Burton doesn't open GitHub issues..

**Comment by mainland** [comment]
I'm sympathetic, but I don't have any more influence over Dan that you do :)

Rather than join the other maintainers of this repository, Dan forked it. That may have been because Ben was not responsive, I don't know. Ideally, we could add Dan as a maintainer to this repository, merge his work, and continue development here.

If @DanBurton were amenable, that would be ideal, and I could try to get Ben to transfer the repository or at least add Dan. I have not had much luck reaching Ben in the past, though.

**Comment by DanBurton** [comment]
@mainland If any maintainers on this repo would like permissions on my fork, just let me know. I'm happy to grant them. You can also feel free to open PRs and pester me if I am unresponsive on them.
